---
#Common variables to all zabbix-servers group hosts

#ZBX Variables
ansible_python_interpreter: /usr/bin/python3
db_name: 'zabbix'
db_user: 'zabbix'
db_password: 'zabbix-server'
db_engine: 'MYSQL'
db_state: 'present'
db_encoding: 'utf8'
db_collation: 'utf8_bin'
ZBX_TIMEZONE: 'America/Argentina/Cordoba'
zabbix_server_name: 'ZBX-MEGA'
zabbix_server: 'localhost'
zabbix_major_version: '4.2'
zabbix_minor_version: '4.2'
ZBX_REPO_URL: 'https://repo.zabbix.com/zabbix/4.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.2-1+bionic_all.deb'
#zabbix_repo_url: 'https://repo.zabbix.com/zabbix/4.2/raspbian/pool/main/z/zabbix-release/zabbix-release_4.2-1+stretch_all.deb'

#NTP Variables
NTP_SERVER: ""

