---
- name: Installing ntp
  apt:
    name: ntp
    state: present
  become: yes

- name: Copying ntp configuration
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    backup: yes
  notify: restart ntp
  become: yes