---

#Zabbix Server Handlers
- name: zabbix-server start
  service: name=zabbix-server state=started
  become: yes

- name: zabbix-server stop
  service: name=zabbix-server state=stopped
  become: yes
  
- name: zabbix-server restart
  service: name=zabbix-server state=restarted
  become: yes

  #Apache2 Handlers
- name: apache2 start
  service: name=apache2 state=started
  become: yes

- name: apache2 stop
  service: name=apache2 state=stopped
  become: yes

- name: apache2 restart
  service: name=apache2 state=restarted
  become: yes

- name: apache2 reload
  service: name=apache2 state=reloaded
  become: yes