---
# Variable setup. Check if a file can be use for all Debian distributions (Debian, Ubuntu and Raspbian because the have the same content.)
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Check if this is the best approach to check if zbx is installed or not and make idempotent creation of db
- name: Check if zabbix is already installed
  stat:
    path: /etc/zabbix
  register: zabbix_server_stats

# Setup/install tasks.
- name: Include Configuration Tasks for RedHat Family Servers
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Configuration Tasks for Debian Family Servers
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include Configuration Tasks for Postgresql Database
  include_tasks: pgsql.yml
  when: db_engine == 'pgsql'

- name: Include Configuration Tasks for Mysql Database
  include_tasks: mysql.yml
  when: db_engine == 'mysql'

# Maybe it would be better to do this with lineinfile module
- name: Copying zabbix_server.conf configuration file into /etc/zabbix
  template:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    backup: yes
  notify: zabbix-server-restart

# Maybe it would be better to do this with lineinfile module
- name: Copying zabbix_agent.conf configuration file into /etc/zabbix
  template:
    src: zabbix_agent.conf
    dest: /etc/zabbix/zabbix_agent.conf
    backup: yes
  notify: zabbix-agent-restart

# Check if this step is right to put here in main or should be put inside Debian and RedHat files
- name: Copying zabbix.conf.php configuration file into /usr/share/zabbix/conf
  template:
    src: zabbix.conf.php
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    backup: yes
  notify: zabbix-server-restart

- name: Copying apache.conf template into /etc/zabbix directory
  template:
    src: apache.conf
    dest: /etc/zabbix/apache.conf
    backup: yes
  notify: apache2-restart
  when: web_server == 'apache'

- name: Starting zabbix server and enabling it on system startup
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - apache2
    - zabbix-server
    - zabbix-agent