---

# Check why linter is showing alerts.

- name: Ensure dependencies are installed.
  yum:
    name:
      - curl
      - git
      - gnupg
      - htop
      - unzip
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: Ensure dependencies are installed.
  dnf:
    name:
      - curl
      - git
      - gnupg
      - htop
      - unzip
    state: present
  when: ansible_pkg_mgr == 'dnf'

- name: Download e install zabbix repositories
  package:
    name: "{{ zabbix_repo_url }}"
    state: present

- name: Install zabbix-server
  yum:
    name:
      - zabbix-server-{{ db_engine }}
      - zabbix-web-{{ db_engine }}
      - zabbix-{{ web_server }}-conf
      - zabbix-agent
    state: present
  when: ansible_pkg_mgr == 'yum' and zabbix_server_version is version('4.3', '>') # check 4.3

- name: Install zabbix-server
  dnf:
    name:
      - zabbix-server-{{ db_engine }}
      - zabbix-web-{{ db_engine }}
      - zabbix-{{ web_server }}-conf
      - zabbix-agent
    state: present
  when: ansible_pkg_mgr == 'dnf' and zabbix_server_version is version('4.3', '>') # check 4.3

- name: Install zabbix-server
  yum:
    name:
      - zabbix-server-{{ db_engine }}
      - zabbix-web-{{ db_engine }}
      - zabbix-{{ web_server }}-conf
      - zabbix-agent
    state: present
  when: ansible_pkg_mgr == 'yum' and zabbix_server_version is version('4.3', '<=') # check 4.3

- name: Install zabbix-server
  dnf:
    name:
      - zabbix-server-{{ db_engine }}
      - zabbix-web-{{ db_engine }}
      - zabbix-{{ web_server }}-conf
      - zabbix-agent
    state: present
  when: ansible_pkg_mgr == 'dnf' and zabbix_server_version is version('4.3', '<=') # check 4.3

# check if packages to install are different between different zabbix versions
