---
- name: Downloading e installing zabbix repositories
  apt:
    deb: "{{ZBX_REPO_URL['RASPBIAN']}}"
    state: present
  become: yes
  when: ansible_lsb['id'] == "Raspbian" and ansible_lsb['codename'] == "stretch"

- name: Downloading e installing zabbix repositories
  apt:
    deb: "{{ZBX_REPO_URL['BIONIC']}}"
    state: present
  become: yes
  when: ansible_lsb['id'] == "Ubuntu" and ansible_lsb['codename'] == "bionic"

- name: Updating repositories and installing zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes
  become: yes

- name: Copying zabbix-agent configuration file in /etc/zabbix
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify: zabbix-agent restart
  become: yes