---

#POSTGRESQL

- name: Installing ansible postgresql module dependencies
  apt: 
    name: python-psycopg2
    state: present
  become: yes
  when: db_engine == 'POSTGRESQL'  

- name: Installing postgresql server
  apt: 
    name: postgresql 
    state: present
  become: yes
  when: db_engine == 'POSTGRESQL'

- name: Creating postgresql database user and password
  become: yes
  become_user: postgres
  postgresql_user: 
    name: {{db_user}}
    password: {{db_password}}
  when: db_engine == 'POSTGRESQL'                 

- name: Creating postgresql database
  become: yes
  become_user: postgres
  postgresql_db: 
    name: {{db_name}} 
    owner: {{db_user}}
    state: {{db_state}}
  when: db_engine == 'POSTGRESQL'


#MYSQL

- name: Installing ansible mysql module dependencies
  apt: 
    name: python-mysqldb 
    state: present
  become: yes
  when: db_engine == 'MYSQL'

- name: Installing mysql server
  apt: 
    name: mysql-server 
    state: present
  become: yes
  when: db_engine == 'MYSQL'

- name: Creating mysql database
  become: yes
  mysql_db: 
    name: {{db_name}}
    state: {{db_state}}
    collation: {{db_collation}}
    encoding: {{db_encoding}}
  when: db_engine == 'MYSQL'

- name: Creating mysql database user and password
  become: yes
  mysql_user: 
    name: {{db_user}}
    password: {{db_password}}
    priv: 'zabbix.*:ALL,GRANT'
    state: present
  when: db_engine == 'MYSQL'