---

#Zabbix Agent Handlers
- name: zabbix-agent start 
  service: name=zabbix-agent state=started
  become: yes

- name: zabbix-agent  stop
  service: name=zabbix-agent state=stopped
  become: yes
  
- name: zabbix-agent restart
  service: name=zabbix-agent state=restarted
  become: yes