---

- name: checking if dhparam already exists
  stat: path={{dhparam_location}}/dhparam.pem
  register: dhparam_stats
  become: yes  

- name: generating Diffie-Hellman parameter for DHE ciphersuites
  shell: "openssl dhparam -out {{dhparam_location}}/dhparam.pem 2048"
  when: dhparam_stats.stat.exists == False
  become: yes  