---
- name: installing software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
  become: yes

- name: adding certbot repositories
  apt_repository:
     repo: ppa:certbot/certbot
  become: yes

- name: installing certbot
  apt:
    name: certbot 
    state: present
    update_cache: yes
  become: yes

#- name: generating certs (first time)
#  shell: "certbot certonly --standalone {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"
#  when: cert_stats.stat.exists == False

- name: generating SSL certificates
  shell: "certbot certonly --webroot -w /var/www/html/ {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"
  become: yes

#Renovacion automatica certificados LetsEncrypt

- name: installing crontab entry for automatic certificates renewal
  cron: name="renovacion automatica certificados letsencrypt" hour="23" minute="30" job="certbot renew --agree-tos" state=present
  become: yes